name: CI

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rustfmt.toml'
      - 'config/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rustfmt.toml'
      - 'config/**'
      - '.github/workflows/**'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  TOOLCHAIN: nightly-2024-10-18

jobs:
  ci:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup toolchain install ${{ env.TOOLCHAIN }}
      - name: Set default toolchain
        run: rustup default ${{ env.TOOLCHAIN }}
      - name: Install rustc-src
        run: rustup component add rust-src
      - name: Install rustc-dev
        run: rustup component add rustc-dev
      - name: Install llvm-tools-preview
        run: rustup component add llvm-tools-preview
      - name: Add clippy
        run: rustup component add clippy
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Run cargo build
        run: cargo build --verbose
      - name: Run cargo test
        run: cargo test --verbose -- --test-threads=1 --nocapture
      - name: Run cargo clippy
        run: cargo clippy --verbose
      - name: Run cargo fmt
        run: cargo fmt -- --check
